import struct

class ImodMesh(object):

    def __init__(self,
        fid = None,
        nObj = None,
        minx_cscale = None,
        minx_ctrans = None,
        debug = 0,
        nVertices = 0,
        nIndices = 0,
        flag = 0,
        type = 0,
        pad = 0,
        vertices = [],
        indices = [],
        **kwargs):
            self.__dict__.update(kwargs)
            self.__dict__.update(locals())
            if self.fid:
                self.read_file()    

    def read_file(self):
        fid = self.fid
        self.nVertices = struct.unpack('>l', fid.read(4))[0]
        self.nIndices = struct.unpack('>l', fid.read(4))[0]
        self.flag = struct.unpack('>l', fid.read(4))[0]
        self.type = struct.unpack('>h', fid.read(2))[0]
        self.pad = struct.unpack('>h', fid.read(2))[0] 
        self.vertices = struct.unpack('>{0}f'.format(3 * self.nVertices),
            fid.read(12 * self.nVertices))
        self.indices = struct.unpack('>{0}l'.format(self.nIndices),
            fid.read(4 * self.nIndices))
        return self

    def export_vrml2(self, fname):
        fid = open(fname, 'w+')
        fid.write('#VRML V2.0 utf8')
        fid.write('# Generated by pyimod')
        fid.write('')
        fid.write('DEF imod_model Transform {')
        fid.write('  children [')
        fid.write('')
        fid.write('#MATERIAL FOR OBJECT:') 

    def dump(self):
        from collections import OrderedDict as od
        for key, value in od(sorted(self.__dict__.items())).iteritems():
            print key, value
        print "\n"

